# {Project Title TBA}📝

![Banner](./assets/banner.jpeg)

## Topic
*What problem are you (or your stakeholder) trying to address?*
📝 <!-- Answer Below -->

Retail annuity products, specifically fixed, variable and indexed annuities, are designed to meet different financial needs related to risk tolerance, income stability, and long-term growth. However, product selection is oftern influenced by a combination of customer demographics (i.e age, income, and retirement horizon) and external economic conditions such as interest rates and inflation, rather than a clear data-driven matching process.

In practice, this leads to measurable inefficiencies:
- Customers nearing retirement (ages 55–70) may select variable annuities despite shorter time horizons, exposing them to unnecessary market volatility.
- Younger or higher-income individuals may underutilize growth-oriented products due to conservative defaults or lack of guidance.
- Periods of rising interest rates can shift product demand toward fixed annuities, but is this relationship being quantified at the customer-segment level?

From a data management and reporting perspective, annuity providers maintain large volumes of structured data (customer profiles, transaction histories, and product allocations), but this data is often used descriptively (reporting past sales) rather than analytically (understanding why certain products are selected and whether those selections align with customer characteristics and market conditions).

This project aims to analyze how specific variables:
- Age (grouped into pre-retirement vs retirement cohorts)
- Income level (segmentented into quantiles)
- Proxy indicators of risk tolerance (derived from financial behavior)
- Macroeconomic conditions (interest rate levels over time)
influence the likelihood of a customer selecting a particular annuity product type.

By integrating customer level financial data with external economic indicators, this analysis will identify statistically significant relationships between customer profiles, market conditions, and product selection patterns. The goal is predictive and explanatory insights that can support:
- targeted product recommendations
- improved segmentation strategies
- and better alignment between customer needs and financial products

## Project Question
*What specific question are you seeking to answer with this project?*
*This is not the same as the questions you ask to limit the scope of the project.*
📝 <!-- Answer Below -->

How do customer demographic(age and income) and macroeconomic conditions(interest rates) influence the liklihood of selecting fixed, variable, or indexed annuity products?

Addition questions:
- How does annuity product selection vary across age groups (<40, 40–55, 55+)?
- Does income level significantly affect the likelihood of choosing higher-risk products (variable annuities)?
- How do changes in interest rates over time impact the distribution of annuity product types?
- Which factors (age, income, or economic conditions) have the greatest predictive power in determining product selection?

## What would an answer look like?
*What is your hypothesized answer to your question?*
📝 <!-- Answer Below -->

- A predictive model outputting probabilities such as: “A 60-year-old with moderate income during high interest rate periods has a 72% probability of selecting a fixed annuity”

- Ranked feature importance:
    - Age -> strongest predictor
    - Interest rate -> secondary
    - Income -> moderate

- Visual confirmation of trends: clear seperation of product types across demographic groups

## Data Sources
*What 3 data sources have you identified for this project?*
*How are you going to relate these datasets?*
📝 <!-- Answer Below -->

Economic Indicators (API) : from Federal Reserve Economic Data (https://fred.stlouisfed.org/)

Key variables: 
- Federal interest rates
- Inflation rate
- Treasury yields

Assign economic conditions to each observation and create low rate vs high rate environments.

bank.csv from Bank Marketing Dataset on Kaggle
https://www.kaggle.com/datasets/janiobachmann/bank-marketing-dataset?resource=download

Key variables:
- age
- job / income proxy
- marital status
= education

Represent customer demographic and financial profiles and create derived features.

Use pandas to generate a simulated annuity products dataset:
- real annuity product selection data is proprietary
- Customer attributes such as age, income, and prevailing interest rates were used to assign annuity product types in a way that reflects realistic market tendencies

## Approach and Analysis
*What is your approach to answering your project question?*
*How will you use the identified data to answer your project question?*
📝 <!-- Start Discussing the project here; you can add as many code cells as you need -->

This project will follow a structured data analytics workflow to examine how customer demographics and economic conditions influence annuity product selection.

1. Data Acquisition and Integration

Three datasets will be used:

A customer financial behavior dataset (CSV file)
Macroeconomic data retrieved via the Federal Reserve Economic Data
A simulated annuity product dataset generated within the notebook

The customer dataset will provide demographic variables such as age and income. Economic data (e.g., interest rates) will be mapped to each observation using a time-based or scenario-based assignment. A simulated dataset will assign annuity product types (fixed, variable, indexed) to each customer using probabilistic rules based on financial assumptions.

2. Data Cleaning and Preprocessing
Handle missing or inconsistent values in customer data
Normalize and clip income values to realistic ranges
Convert continuous variables into categorical features:
Age → grouped into (<40, 40–55, 55+)
Income → segmented into low, medium, and high tiers
Ensure all datasets are aligned in structure for merging
3. Feature Engineering
Create derived variables:
Age group
Income tier
Interest rate category (low vs high rate environment)
Generate the target variable:
annuity_product (fixed, variable, indexed) using probabilistic assignment
Merge product metadata (risk level, return type, fee level) into the final dataset
4. Exploratory Data Analysis (EDA)

EDA will be conducted to identify patterns and relationships:

Distribution of annuity product types across age groups
Relationship between income tiers and product selection
Impact of interest rate levels on product distribution
Correlation analysis between variables

Visualizations will include:

Bar charts (product type vs demographic groups)
Heatmaps (income vs product type)
Line plots (interest rates vs product trends)
5. Predictive Modeling

A classification model will be developed to predict annuity product selection:

Logistic regression and/or decision tree classifier
Input variables:
Age group
Income tier
Interest rate
Output:
Probability of selecting each annuity product type
6. Model Evaluation and Interpretation
Evaluate model performance using accuracy and confusion matrix
Analyze feature importance to determine which variables most influence product selection
Interpret results in the context of financial decision-making
7. Insight Generation

The final step will translate analytical results into business insights:

Identify which customer segments are most likely to choose each product type
Evaluate how economic conditions shift product preferences
Discuss how these insights could support better targeting and product recommendations in an annuity business context

## Resources and References
*What resources and references have you used for this project?*
📝 <!-- Answer Below -->

Kaggle - Bank Marketing dataset https://www.kaggle.com/datasets/janiobachmann/bank-marketing-dataset?resource=download
Federal Reserve Economic Data (https://fred.stlouisfed.org/)
ChatGPT

In [2]:
# ⚠️ Make sure you run this cell at the end of your notebook before every submission!
!jupyter nbconvert --to python source.ipynb

[NbConvertApp] Converting notebook source.ipynb to python
[NbConvertApp] Writing 1271 bytes to source.py

### Imports

In [3]:
import pandas as pd
import numpy as np

Generate simulated dataset

In [6]:
customers = pd.DataFrame({
    "customer_id": range(1, n+1),
    "age": np.random.randint(25, 75, n),
    "income": np.random.normal(60000, 20000, n).clip(20000, 150000),
    "risk_score": np.random.randint(1, 10, n),  # 1 = low risk tolerance
    "retirement_horizon": np.random.randint(1, 40, n),  # years
})

products = pd.DataFrame({
    "product_id": [1, 2, 3],
    "product_type": ["fixed", "variable", "indexed"],
    "risk_level": ["low", "high", "medium"],
    "avg_return": [0.03, 0.07, 0.05],
    "fee_percent": [0.01, 0.025, 0.015],
    "liquidity": ["low", "high", "medium"]
})

n_policies = 2000

policies = pd.DataFrame({
    "policy_id": range(1, n_policies+1),
    "customer_id": np.random.choice(customers["customer_id"], n_policies),
    "product_id": np.random.choice(products["product_id"], n_policies),
    "year": np.random.choice(range(2015, 2025), n_policies),
    "premium": np.random.normal(20000, 10000, n_policies).clip(2000, 100000)
})

def assign_product(customer):
    probs = [0.33, 0.33, 0.34]  # fixed, variable, indexed

    # Risk score influence
    if customer["risk_score"] <= 3:
        probs[0] += 0.3  # fixed
    elif customer["risk_score"] >= 7:
        probs[1] += 0.3  # variable

    # Retirement horizon
    if customer["retirement_horizon"] < 10:
        probs[0] += 0.2
    else:
        probs[1] += 0.1

    probs = np.array(probs) / sum(probs)
    return np.random.choice([1, 2, 3], p=probs)

interest_rates = {
    2015: 0.25, 2016: 0.5, 2017: 1.0, 2018: 2.0,
    2019: 2.5, 2020: 0.25, 2021: 0.25, 2022: 3.0,
    2023: 5.0, 2024: 5.25
}

policies["interest_rate"] = policies["year"].map(interest_rates)

df = policies.merge(customers, on="customer_id")
df = df.merge(products, on="product_id")

In [7]:
df.head(10)

,policy_id,customer_id,product_id,year,premium,interest_rate,age,income,risk_score,retirement_horizon,product_type,risk_level,avg_return,fee_percent,liquidity
0,1,923,2,2015,10179.805028,0.25,48,43535.898054,3,3,variable,high,0.07,0.025,high
1,2,819,2,2024,13132.676044,5.25,37,54236.557077,3,13,variable,high,0.07,0.025,high
2,3,832,2,2015,23849.664160,0.25,71,56026.297741,1,4,variable,high,0.07,0.025,high
3,4,52,3,2020,27985.666731,0.25,67,83898.442697,5,19,indexed,medium,0.05,0.015,medium
4,5,209,3,2015,31209.365124,0.25,50,63142.173890,6,17,indexed,medium,0.05,0.015,medium
5,6,550,1,2019,35696.285869,2.50,55,40484.509852,5,21,fixed,low,0.03,0.010,low
6,7,612,2,2018,19325.534414,2.00,74,98423.352411,5,18,variable,high,0.07,0.025,high
7,8,705,1,2019,31936.117552,2.50,66,59391.193370,1,34,fixed,low,0.03,0.010,low
8,9,402,3,2021,16576.951566,0.25,62,68920.619105,4,13,indexed,medium,0.05,0.015,medium
9,10,191,3,2020,29020.913116,0.25,37,54707.146274,2,37,indexed,medium,0.05,0.015,medium

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   policy_id           2000 non-null   int64
 1   customer_id         2000 non-null   int64
 2   product_id          2000 non-null   int64
 3   year                2000 non-null   int64
 4   premium             2000 non-null   float64
 5   interest_rate       2000 non-null   float64
 6   age                 2000 non-null   int32
 7   income              2000 non-null   float64
 8   risk_score          2000 non-null   int32
 9   retirement_horizon  2000 non-null   int32
 10  product_type        2000 non-null   str
 11  risk_level          2000 non-null   str
 12  avg_return          2000 non-null   float64
 13  fee_percent         2000 non-null   float64
 14  liquidity           2000 non-null   str
dtypes: float64(5), int32(3), int64(4), str(3)
memory usage: 211.1 KB

In [9]:
df.describe()

,policy_id,customer_id,product_id,year,premium,interest_rate,age,income,risk_score,retirement_horizon,avg_return,fee_percent
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,505.914000,1.997500,2019.514000,20048.875250,2.012125,50.222000,60802.286604,4.882500,19.895000,0.049680,0.016538
std,577.494589,285.494568,0.822698,2.861275,9363.875442,1.823111,14.409946,19558.305496,2.572742,11.303754,0.016286,0.006204
min,1.000000,1.000000,1.000000,2015.000000,2000.000000,0.250000,25.000000,20000.000000,1.000000,1.000000,0.030000,0.010000
25%,500.750000,257.750000,1.000000,2017.000000,13437.182058,0.250000,38.000000,47185.365045,3.000000,10.750000,0.030000,0.010000
50%,1000.500000,503.500000,2.000000,2019.500000,20078.878254,2.000000,50.000000,60801.592344,5.000000,20.000000,0.050000,0.015000
75%,1500.250000,751.500000,3.000000,2022.000000,26359.331965,3.000000,63.000000,74029.937362,7.000000,30.000000,0.070000,0.025000
max,2000.000000,999.000000,3.000000,2024.000000,51577.712830,5.250000,74.000000,133154.036080,9.000000,39.000000,0.070000,0.025000

In [14]:
df.to_csv("data/annuity.csv", index=False)
customers.to_csv("data/customers.csv", index=False)
products.to_csv("data/products.csv", index=False)
policies.to_csv("data/policies.csv", index=False)

In [13]:
annuity_data = pd.read_csv("data/annuity.csv")
annuity_data.head()

,policy_id,customer_id,product_id,year,premium,interest_rate,age,income,risk_score,retirement_horizon,product_type,risk_level,avg_return,fee_percent,liquidity
0,1,923,2,2015,10179.805028,0.25,48,43535.898054,3,3,variable,high,0.07,0.025,high
1,2,819,2,2024,13132.676044,5.25,37,54236.557077,3,13,variable,high,0.07,0.025,high
2,3,832,2,2015,23849.664160,0.25,71,56026.297741,1,4,variable,high,0.07,0.025,high
3,4,52,3,2020,27985.666731,0.25,67,83898.442697,5,19,indexed,medium,0.05,0.015,medium
4,5,209,3,2015,31209.365124,0.25,50,63142.173890,6,17,indexed,medium,0.05,0.015,medium

The simulated datasets (customers,products, and policies) were exported as CSV files to support reproducibility and validation. These files are meant to represent a relational data structure similar to a real world annuity data environment.

# Exploratory Data Analysis
This section explores the structure, distribution, and relationships within the simulated annuity dataset. The goal is to identify patterns, detect data quality issues, and understand how customer characteristics and economic conditions relate to annuity product selection.